site_name: Engineering Journal KB
site_url: https://newcomb-labs.github.io/engineering-journal-kb/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest

plugins:
  - search
  - roamlinks

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
